# Required metadata
sonar.projectKey=ybayraktarb_Randevux
sonar.organization=ybayraktarb

# Appearance
sonar.projectName=Randevux
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src,app,lib,shared
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/public/**,**/*.test.ts,**/*.test.tsx,**/__tests__/**,playwright.config.ts,vitest.config.ts,e2e/**

# Path to tests
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# JavaScript and TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
