apiVersion: v1
kind: Service
metadata:
  name: randesk-web-svc
  namespace: default
  labels:
    app: randesk-web
spec:
  type: ClusterIP
  selector:
    app: randesk-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
